version = 0.1
[default.deploy.parameters]
stack_name = "cerebro-reverse-proxy"
resolve_s3 = true
s3_prefix = "cerebro-reverse-proxy"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
